version: '3.8'
services:

  # PHP App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: absensi-app
    container_name: absensi-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - absensi-network

  # Nginx Web Server
  web:
    image: nginx:alpine
    container_name: absensi-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - absensi-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: absensi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-absensi}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-root}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - absensi-network

  # Redis
  redis:
    image: redis:alpine
    container_name: absensi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - absensi-network

  # Mailpit (Email testing)
  mailpit:
    image: axllent/mailpit
    container_name: absensi-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - absensi-network

networks:
  absensi-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
